# Generated by Django 3.1.6 on 2021-02-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Userdetail', '0007_auto_20210215_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='curru',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tag', serialize=False, to='auth.user')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='cuser',
        ),
    ]
