# Generated by Django 3.1.6 on 2021-02-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Userdetail', '0008_auto_20210221_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuser',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tag', serialize=False, to='auth.user')),
                ('accno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='curru',
        ),
    ]
