# Generated by Django 3.1.6 on 2021-02-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0009_auto_20210221_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuser',
        ),
    ]
