# Generated by Django 3.1.6 on 2021-02-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
