# Generated by Django 3.1.6 on 2021-02-21 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created_by',
            field=models.CharField(default='staff', max_length=250),
        ),
    ]
