# Generated by Django 3.1.6 on 2021-02-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0014_auto_20210222_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
