# Generated by Django 3.1.6 on 2021-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0015_auto_20210222_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
